# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Visualize"
license = "MIT"
licenselink = "https://github.com/aswinkarthik93/visualize/blob/master/LICENSE.md"
description = "A port of Visualize theme to hugo"
homepage = ""
tags = []
features = []
min_version = "0.26"

[author]
  name = "Aswin Karthik S"
  homepage = ""

# If porting an existing theme
[original]
  name = "Visualize"
  homepage = "https://templated.co/visualize"
  repo = ""
